name: Build and Push Docker Image

on:
  # push:
  #   branches:
  #     - main  # 默认主分支，可以根据需要修改
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: '自定义版本号 (留空则使用 GitHub 引用名称)'
        required: false

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print GitHub context
        run: |
          echo "repository: ${{ github.repository }}"
          echo "actor: ${{ github.actor }}"
          echo "ref_name: ${{ github.ref_name }}"
          echo "custom_version: ${{ github.event.inputs.version }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 确定版本标签
        id: tags
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${{ github.ref_name }}"
          fi
          
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "tags=shine1223/98t:$VERSION,shine1223/98t:latest" >> $GITHUB_OUTPUT

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.tags.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
